-- Generated by Pumpkin

local data = {}

local path = ...
if type(path) ~= "string" then
	path = "."
end
data.image = love.graphics.newImage(path.."cell.sprite.png")
data.image:setFilter("nearest", "nearest")
data.animations = {
	body_hit={
		[0]={u=0, v=0, w=347, h=379, offsetX=174, offsetY=174, duration=0.0333333},
		[1]={u=0, v=379, w=347, h=379, offsetX=174, offsetY=174, duration=0.0333333},
		[2]={u=0, v=758, w=347, h=379, offsetX=174, offsetY=174, duration=0.0333333},
		[3]={u=0, v=1137, w=347, h=379, offsetX=174, offsetY=174, duration=0.0333333},
		[4]={u=0, v=1516, w=347, h=379, offsetX=174, offsetY=174, duration=0.0333333},
		[5]={u=483, v=0, w=347, h=379, offsetX=174, offsetY=174, duration=0.0333333},
		[6]={u=830, v=0, w=347, h=379, offsetX=174, offsetY=174, duration=0.0333333},
		[7]={u=1177, v=0, w=347, h=379, offsetX=174, offsetY=174, duration=0.0333333},
		[8]={u=1524, v=0, w=347, h=379, offsetX=174, offsetY=174, duration=0.0333333},
		[9]={u=347, v=532, w=347, h=379, offsetX=174, offsetY=174, duration=0.0333333},
		[10]={u=347, v=911, w=347, h=379, offsetX=174, offsetY=174, duration=0.0333333},
		[11]={u=347, v=1290, w=347, h=379, offsetX=174, offsetY=174, duration=0.0333333},
		[12]={u=483, v=1669, w=347, h=379, offsetX=174, offsetY=174, duration=0.0333333},
		scale=1
	},
	icon_link={
		[0]={u=1384, v=694, w=83, h=83, offsetX=41, offsetY=40, duration=0.0333333},
		[1]={u=1380, v=931, w=83, h=83, offsetX=41, offsetY=40, duration=0.0333333},
		[2]={u=1380, v=1014, w=83, h=83, offsetX=41, offsetY=40, duration=0.0333333},
		[3]={u=1380, v=1097, w=83, h=83, offsetX=41, offsetY=40, duration=0.0333333},
		[4]={u=926, v=1494, w=83, h=83, offsetX=41, offsetY=40, duration=0.0666667},
		[5]={u=1380, v=1097, w=83, h=83, offsetX=41, offsetY=40, duration=0.0333333},
		[6]={u=1380, v=1014, w=83, h=83, offsetX=41, offsetY=40, duration=0.0333333},
		[7]={u=1380, v=931, w=83, h=83, offsetX=41, offsetY=40, duration=0.0333333},
		scale=1
	},
	body_grey_glow={
		[0]={u=694, v=500, w=128, h=224, offsetX=65, offsetY=106, duration=0.0833333},
		scale=1
	},
	body_grey={
		[0]={u=1208, v=1105, w=96, h=192, offsetX=49, offsetY=92, duration=0.0833333},
		[1]={u=830, v=1109, w=96, h=192, offsetX=49, offsetY=92, duration=0.0833333},
		[2]={u=926, v=1142, w=96, h=192, offsetX=49, offsetY=92, duration=0.0833333},
		[3]={u=830, v=1109, w=96, h=192, offsetX=49, offsetY=92, duration=0.0833333},
		[4]={u=926, v=1142, w=96, h=192, offsetX=49, offsetY=92, duration=0.0833333},
		scale=1
	},
	heart={
		[0]={u=830, v=1301, w=96, h=160, offsetX=49, offsetY=81, duration=0.0833333},
		[1]={u=1100, v=1232, w=96, h=160, offsetX=49, offsetY=81, duration=0.0833333},
		[2]={u=926, v=1334, w=96, h=160, offsetX=49, offsetY=81, duration=0.0833333},
		[3]={u=1100, v=1232, w=96, h=160, offsetX=49, offsetY=81, duration=0.0833333},
		[4]={u=926, v=1334, w=96, h=160, offsetX=49, offsetY=81, duration=0.0833333},
		scale=1
	},
	heart_glow={
		[0]={u=694, v=724, w=128, h=192, offsetX=65, offsetY=91, duration=0.0833333},
		scale=1
	},
	trail={
		[0]={u=485, v=484, w=22, h=22, offsetX=11, offsetY=11, duration=0.0333333},
		scale=1
	},
	flesheater_hit={
		[0]={u=1034, v=924, w=66, h=82, offsetX=33, offsetY=44, duration=0.0333333},
		[1]={u=389, v=1895, w=84, h=102, offsetX=44, offsetY=54, duration=0.0333333},
		[2]={u=1868, v=532, w=178, h=178, offsetX=88, offsetY=92, duration=0.0333333},
		[3]={u=1471, v=379, w=236, h=240, offsetX=118, offsetY=124, duration=0.0333333},
		[4]={u=830, v=654, w=270, h=270, offsetX=135, offsetY=137, duration=0.0333333},
		[5]={u=830, v=379, w=277, h=275, offsetX=141, offsetY=140, duration=0.0666667},
		[6]={u=830, v=654, w=270, h=270, offsetX=135, offsetY=137, duration=0.0333333},
		[7]={u=1470, v=619, w=236, h=240, offsetX=118, offsetY=124, duration=0.0333333},
		[8]={u=1107, v=500, w=277, h=275, offsetX=141, offsetY=140, duration=0.0333333},
		scale=1
	},
	spikey_hit={
		[0]={u=1359, v=379, w=112, h=112, offsetX=53, offsetY=49, duration=0.0333333},
		[1]={u=1107, v=379, w=126, h=120, offsetX=64, offsetY=49, duration=0.0333333},
		[2]={u=1322, v=777, w=148, h=154, offsetX=71, offsetY=73, duration=0.0333333},
		[3]={u=1871, v=0, w=174, h=180, offsetX=87, offsetY=88, duration=0.0333333},
		[4]={u=1862, v=710, w=178, h=183, offsetX=89, offsetY=89, duration=0.0666667},
		[5]={u=1871, v=0, w=174, h=180, offsetX=87, offsetY=88, duration=0.0333333},
		[6]={u=1679, v=1041, w=148, h=154, offsetX=71, offsetY=73, duration=0.0333333},
		[7]={u=1233, v=379, w=126, h=120, offsetX=64, offsetY=49, duration=0.0333333},
		[8]={u=1862, v=924, w=178, h=183, offsetX=89, offsetY=89, duration=0.0333333},
		scale=1
	},
	head={
		[0]={u=1706, v=667, w=156, h=163, offsetX=71, offsetY=69, duration=0.0333333},
		[1]={u=1706, v=830, w=156, h=163, offsetX=71, offsetY=69, duration=0.0333333},
		[2]={u=1862, v=1107, w=156, h=163, offsetX=71, offsetY=69, duration=0.0333333},
		scale=1
	},
	head_glow={
		[0]={u=1100, v=775, w=222, h=172, offsetX=112, offsetY=80, duration=0.0666667},
		[1]={u=1470, v=859, w=214, h=70, offsetX=108, offsetY=-4, duration=0.0666667},
		[2]={u=1100, v=775, w=222, h=172, offsetX=112, offsetY=80, duration=0.0666667},
		scale=1
	},
	port={
		[0]={u=482, v=379, w=106, h=105, offsetX=54, offsetY=54, duration=0.0333333},
		scale=1
	},
	port_glow={
		[0]={u=256, v=1895, w=133, h=132, offsetX=75, offsetY=48, duration=0.0333333},
		scale=1
	},
	flesheater={
		[0]={u=1034, v=1006, w=66, h=93, offsetX=33, offsetY=43, duration=0.0666667},
		[1]={u=1032, v=1099, w=66, h=93, offsetX=33, offsetY=43, duration=0.0666667},
		[2]={u=694, v=1461, w=66, h=93, offsetX=33, offsetY=43, duration=0.0666667},
		scale=1
	},
	flesheater_glow={
		[0]={u=723, v=379, w=98, h=102, offsetX=49, offsetY=47, duration=0.0666667},
		[1]={u=1208, v=947, w=98, h=102, offsetX=49, offsetY=47, duration=0.0666667},
		[2]={u=723, v=379, w=98, h=102, offsetX=49, offsetY=47, duration=0.0666667},
		scale=1
	},
	body={
		[0]={u=1871, v=180, w=161, h=176, offsetX=80, offsetY=86, duration=0.0666667},
		[1]={u=1871, v=356, w=161, h=176, offsetX=80, offsetY=86, duration=0.0666667},
		[2]={u=1707, v=491, w=161, h=176, offsetX=80, offsetY=86, duration=0.0666667},
		scale=1
	},
	body_glow={
		[0]={u=830, v=924, w=204, h=78, offsetX=101, offsetY=27, duration=0.0666667},
		[1]={u=830, v=1041, w=202, h=68, offsetX=101, offsetY=26, duration=0.0666667},
		[2]={u=1470, v=929, w=209, h=176, offsetX=103, offsetY=86, duration=0.0666667},
		scale=1
	},
	gun={
		[0]={u=1707, v=379, w=58, h=110, offsetX=27, offsetY=80, duration=0.0666667},
		[1]={u=347, v=1669, w=108, h=226, offsetX=53, offsetY=139, duration=0.0666667},
		[2]={u=694, v=916, w=108, h=226, offsetX=53, offsetY=139, duration=0.0666667},
		[3]={u=1022, v=1373, w=70, h=156, offsetX=34, offsetY=126, duration=0.0666667},
		[4]={u=140, v=1895, w=58, h=140, offsetX=27, offsetY=110, duration=0.0666667},
		[5]={u=1707, v=379, w=58, h=110, offsetX=27, offsetY=80, duration=0.0666667},
		scale=1
	},
	gun_idle={
		[0]={u=1707, v=379, w=58, h=110, offsetX=28, offsetY=80, duration=0.0666667},
		scale=1
	},
	gun_bounce_idle={
		[0]={u=1765, v=379, w=58, h=110, offsetX=30, offsetY=82, duration=0.0666667},
		scale=1
	},
	gun_bounce_fire={
		[0]={u=1765, v=379, w=58, h=110, offsetX=30, offsetY=82, duration=0.0666667},
		[1]={u=1384, v=532, w=86, h=162, offsetX=44, offsetY=132, duration=0.0666667},
		[2]={u=1100, v=1006, w=108, h=226, offsetX=55, offsetY=140, duration=0.0666667},
		[3]={u=830, v=1461, w=96, h=166, offsetX=52, offsetY=136, duration=0.0666667},
		[4]={u=198, v=1895, w=58, h=138, offsetX=30, offsetY=110, duration=0.0666667},
		[5]={u=1322, v=931, w=58, h=110, offsetX=30, offsetY=82, duration=0.0666667},
		scale=1
	},
	bullet_glow={
		[0]={u=1304, v=1115, w=76, h=76, offsetX=38, offsetY=36, duration=0.0666667},
		[1]={u=1306, v=1041, w=74, h=74, offsetX=37, offsetY=35, duration=0.0666667},
		[2]={u=1022, v=1192, w=78, h=80, offsetX=39, offsetY=39, duration=0.0666667},
		[3]={u=1022, v=1297, w=74, h=76, offsetX=36, offsetY=35, duration=0.0666667},
		scale=1
	},
	bullet={
		[0]={u=389, v=484, w=32, h=32, offsetX=16, offsetY=16, duration=0.0666667},
		[1]={u=347, v=484, w=32, h=32, offsetX=16, offsetY=16, duration=0.0666667},
		[2]={u=421, v=484, w=32, h=32, offsetX=16, offsetY=16, duration=0.0666667},
		[3]={u=453, v=484, w=32, h=32, offsetX=16, offsetY=16, duration=0.0666667},
		scale=1
	},
	bullet_bounce={
		[0]={u=347, v=2027, w=68, h=16, offsetX=34, offsetY=8, duration=0.0666667},
		[1]={u=415, v=2027, w=68, h=16, offsetX=34, offsetY=8, duration=0.0666667},
		[2]={u=256, v=2027, w=68, h=16, offsetX=34, offsetY=8, duration=0.0666667},
		[3]={u=415, v=2027, w=68, h=16, offsetX=34, offsetY=8, duration=0.0666667},
		scale=1
	},
	body_bullet={
		[0]={u=485, v=506, w=23, h=22, offsetX=12, offsetY=11, duration=0.0666667},
		[1]={u=507, v=484, w=22, h=22, offsetX=12, offsetY=11, duration=0.0666667},
		[2]={u=508, v=506, w=23, h=22, offsetX=12, offsetY=11, duration=0.0666667},
		[3]={u=529, v=484, w=23, h=22, offsetX=12, offsetY=11, duration=0.0666667},
		scale=1
	},
	spikey={
		[0]={u=347, v=0, w=135, h=121, offsetX=67, offsetY=60, duration=0.0666667},
		[1]={u=347, v=121, w=135, h=121, offsetX=67, offsetY=60, duration=0.0666667},
		[2]={u=347, v=242, w=135, h=121, offsetX=67, offsetY=60, duration=0.0666667},
		[3]={u=347, v=363, w=135, h=121, offsetX=67, offsetY=60, duration=0.0666667},
		[4]={u=588, v=379, w=135, h=121, offsetX=67, offsetY=60, duration=0.0666667},
		[5]={u=347, v=363, w=135, h=121, offsetX=67, offsetY=60, duration=0.133333},
		[6]={u=347, v=242, w=135, h=121, offsetX=67, offsetY=60, duration=0.0666667},
		[7]={u=347, v=121, w=135, h=121, offsetX=67, offsetY=60, duration=0.0666667},
		scale=1
	},
	spikey_glow={
		[0]={u=0, v=1895, w=140, h=142, offsetX=70, offsetY=69, duration=0.0333333},
		scale=1
	},
}
data.quad = love.graphics.newQuad(0, 0, 1, 1, data.image:getWidth(), data.image:getHeight())

return data
