-- Generated by Pumpkin

local data = {}

local path = ...
if type(path) ~= "string" then
	path = "."
end
data.image = love.graphics.newImage(path.."cell.sprite2.png")
data.image:setFilter("nearest", "nearest")
data.animations = {
	explosion={
		[0]={u=0, v=0, w=506, h=494, offsetX=254, offsetY=244, duration=0.0666667},
		[1]={u=506, v=0, w=506, h=494, offsetX=254, offsetY=244, duration=0.0666667},
		[2]={u=0, v=494, w=230, h=216, offsetX=121, offsetY=112, duration=0.0666667},
		[3]={u=230, v=494, w=168, h=182, offsetX=83, offsetY=65, duration=0.0666667},
		[4]={u=230, v=676, w=124, h=152, offsetX=60, offsetY=61, duration=0.0666667},
		[5]={u=506, v=494, w=506, h=494, offsetX=254, offsetY=244, duration=0.0666667},
		scale=1
	},
}
data.quad = love.graphics.newQuad(0, 0, 1, 1, data.image:getWidth(), data.image:getHeight())

return data
