-- Generated by Pumpkin

local data = {}

local path = ...
if type(path) ~= "string" then
	path = "."
end
data.image = love.graphics.newImage(path.."cell.sprite.png")
data.image:setFilter("nearest", "nearest")
data.animations = {
	body_glow={
		[0]={u=0, v=224, w=128, h=224, offsetX=65, offsetY=115, duration=0.0666667},
		[1]={u=0, v=0, w=128, h=224, offsetX=65, offsetY=115, duration=0.0666667},
		[2]={u=0, v=448, w=128, h=224, offsetX=65, offsetY=115, duration=0.0666667},
		[3]={u=0, v=224, w=128, h=224, offsetX=65, offsetY=115, duration=0.0666667},
		[4]={u=0, v=448, w=128, h=224, offsetX=65, offsetY=115, duration=0.0666667},
		scale=1
	},
	body_grey={
		[0]={u=320, v=576, w=96, h=190, offsetX=51, offsetY=101, duration=0.0666667},
		[1]={u=224, v=640, w=96, h=192, offsetX=51, offsetY=101, duration=0.0666667},
		[2]={u=272, v=832, w=96, h=192, offsetX=51, offsetY=101, duration=0.0666667},
		[3]={u=368, v=832, w=96, h=192, offsetX=51, offsetY=101, duration=0.0666667},
		[4]={u=400, v=382, w=96, h=190, offsetX=51, offsetY=101, duration=0.0666667},
		scale=1
	},
	body_grey_glow={
		[0]={u=0, v=672, w=128, h=224, offsetX=67, offsetY=116, duration=0.0666667},
		[1]={u=128, v=192, w=128, h=224, offsetX=67, offsetY=116, duration=0.0666667},
		[2]={u=128, v=416, w=128, h=224, offsetX=67, offsetY=116, duration=0.0666667},
		[3]={u=128, v=192, w=128, h=224, offsetX=67, offsetY=116, duration=0.0666667},
		[4]={u=128, v=416, w=128, h=224, offsetX=67, offsetY=116, duration=0.0666667},
		scale=1
	},
	body={
		[0]={u=128, v=0, w=96, h=192, offsetX=49, offsetY=103, duration=0.0666667},
		[1]={u=128, v=640, w=96, h=192, offsetX=49, offsetY=103, duration=0.0666667},
		[2]={u=384, v=192, w=96, h=190, offsetX=49, offsetY=103, duration=0.0666667},
		[3]={u=128, v=640, w=96, h=192, offsetX=49, offsetY=103, duration=0.0666667},
		[4]={u=384, v=192, w=96, h=190, offsetX=49, offsetY=103, duration=0.0666667},
		scale=1
	},
	head_glow={
		[0]={u=464, v=812, w=144, h=144, offsetX=73, offsetY=71, duration=0.0666667},
		[1]={u=224, v=0, w=144, h=144, offsetX=73, offsetY=71, duration=0.0666667},
		[2]={u=496, v=352, w=144, h=144, offsetX=73, offsetY=71, duration=0.0666667},
		[3]={u=464, v=812, w=144, h=144, offsetX=73, offsetY=71, duration=0.0666667},
		[4]={u=496, v=352, w=144, h=144, offsetX=73, offsetY=71, duration=0.0666667},
		scale=1
	},
	head={
		[0]={u=0, v=896, w=112, h=112, offsetX=59, offsetY=58, duration=0.0666667},
		[1]={u=112, v=896, w=112, h=112, offsetX=59, offsetY=58, duration=0.0666667},
		[2]={u=576, v=160, w=112, h=112, offsetX=59, offsetY=58, duration=0.0666667},
		[3]={u=112, v=896, w=112, h=112, offsetX=59, offsetY=58, duration=0.0666667},
		[4]={u=576, v=160, w=112, h=112, offsetX=59, offsetY=58, duration=0.0666667},
		scale=1
	},
	heart_glow={
		[0]={u=256, v=192, w=128, h=192, offsetX=63, offsetY=93, duration=0.0666667},
		[1]={u=368, v=0, w=128, h=192, offsetX=63, offsetY=93, duration=0.0666667},
		[2]={u=272, v=384, w=128, h=192, offsetX=63, offsetY=93, duration=0.0666667},
		[3]={u=368, v=0, w=128, h=192, offsetX=63, offsetY=93, duration=0.0666667},
		[4]={u=272, v=384, w=128, h=192, offsetX=63, offsetY=93, duration=0.0666667},
		scale=1
	},
	heart={
		[0]={u=480, v=192, w=96, h=160, offsetX=49, offsetY=80, duration=0.0666667},
		[1]={u=496, v=0, w=96, h=160, offsetX=49, offsetY=80, duration=0.0666667},
		[2]={u=416, v=572, w=96, h=160, offsetX=49, offsetY=80, duration=0.0666667},
		[3]={u=496, v=0, w=96, h=160, offsetX=49, offsetY=80, duration=0.0666667},
		[4]={u=416, v=572, w=96, h=160, offsetX=49, offsetY=80, duration=0.0666667},
		scale=1
	},
	trail_glow={
		[0]={u=224, v=896, w=48, h=48, offsetX=23, offsetY=25, duration=0.0666667},
		[1]={u=224, v=144, w=48, h=48, offsetX=23, offsetY=25, duration=0.0666667},
		[2]={u=224, v=896, w=48, h=48, offsetX=23, offsetY=25, duration=0.0666667},
		[3]={u=224, v=944, w=46, h=46, offsetX=22, offsetY=24, duration=0.0666667},
		[4]={u=272, v=144, w=42, h=42, offsetX=20, offsetY=22, duration=0.0666667},
		[5]={u=224, v=944, w=46, h=46, offsetX=22, offsetY=24, duration=0.0666667},
		scale=1
	},
	trail={
		[0]={u=0, v=1008, w=9, h=9, offsetX=5, offsetY=4, duration=0.0666667},
		[1]={u=9, v=1008, w=9, h=9, offsetX=5, offsetY=4, duration=0.0666667},
		[2]={u=18, v=1008, w=9, h=9, offsetX=5, offsetY=4, duration=0.0666667},
		[3]={u=27, v=1008, w=9, h=9, offsetX=5, offsetY=4, duration=0.0666667},
		[4]={u=36, v=1008, w=9, h=9, offsetX=5, offsetY=4, duration=0.0666667},
		[5]={u=45, v=1008, w=9, h=9, offsetX=5, offsetY=4, duration=0.0666667},
		scale=1
	},
	flesheater={
		[0]={u=416, v=732, w=64, h=80, offsetX=33, offsetY=39, duration=0.0333333},
		[1]={u=480, v=732, w=64, h=80, offsetX=33, offsetY=39, duration=0.0333333},
		[2]={u=592, v=272, w=64, h=80, offsetX=33, offsetY=39, duration=0.0333333},
		[3]={u=480, v=732, w=64, h=80, offsetX=33, offsetY=39, duration=0.0333333},
		[4]={u=656, v=272, w=64, h=80, offsetX=33, offsetY=39, duration=0.0333333},
		scale=1
	},
	flesheater_glow={
		[0]={u=592, v=0, w=96, h=112, offsetX=47, offsetY=54, duration=0.0333333},
		[1]={u=688, v=0, w=96, h=112, offsetX=47, offsetY=54, duration=0.0333333},
		[2]={u=688, v=112, w=96, h=112, offsetX=47, offsetY=54, duration=0.0333333},
		[3]={u=512, v=496, w=96, h=112, offsetX=47, offsetY=54, duration=0.0333333},
		[4]={u=512, v=608, w=96, h=112, offsetX=47, offsetY=54, duration=0.0333333},
		scale=1
	},
	bullet={
		[0]={u=224, v=990, w=32, h=32, offsetX=16, offsetY=17, duration=0.0333333},
		[1]={u=314, v=144, w=28, h=28, offsetX=14, offsetY=16, duration=0.0333333},
		scale=1
	},
	bullet_glow={
		[0]={u=128, v=832, w=63, h=64, offsetX=31, offsetY=32, duration=0.0333333},
		[1]={u=191, v=832, w=63, h=64, offsetX=31, offsetY=32, duration=0.0333333},
		scale=1
	},
}
data.quad = love.graphics.newQuad(0, 0, 1, 1, data.image:getWidth(), data.image:getHeight())

return data
